name: CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read    

env:
  AZURE_RESOURCEGROUP_NAME: rg-rag-demo
  ENVIRONMENT: dev
  REGION: canadaeast  

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # # azd required
      # AZURE_CLIENT_ID: # ${{ vars.AZURE_CLIENT_ID }}
      # AZURE_TENANT_ID: # ${{ vars.AZURE_TENANT_ID }}
      # AZURE_SUBSCRIPTION_ID: # ${{ vars.AZURE_SUBSCRIPTION_ID }}
      # AZURE_ENV_NAME: # ${{ vars.AZURE_ENV_NAME }}
      # AZURE_LOCATION: # ${{ vars.AZURE_LOCATION }}
      # # project specific
      # ALLOWED_ORIGIN: ${{ vars.ALLOWED_ORIGIN }}
      # AZURE_APP_SERVICE_SKU: ${{ vars.AZURE_APP_SERVICE_SKU }}
      # AZURE_AUTH_TENANT_ID: ${{ vars.AZURE_AUTH_TENANT_ID }}
      # AZURE_CLIENT_APP_ID: ${{ vars.AZURE_CLIENT_APP_ID }}
      # AZURE_ENFORCE_ACCESS_CONTROL: ${{ vars.AZURE_ENFORCE_ACCESS_CONTROL }}
      # AZURE_FORMRECOGNIZER_RESOURCE_GROUP: ${{ vars.AZURE_FORMRECOGNIZER_RESOURCE_GROUP }}
      # AZURE_FORMRECOGNIZER_SERVICE: ${{ vars.AZURE_FORMRECOGNIZER_SERVICE }}
      # AZURE_FORMRECOGNIZER_SKU: ${{ vars.AZURE_FORMRECOGNIZER_SKU }}
      # AZURE_KEY_VAULT_NAME: ${{ vars.AZURE_KEY_VAULT_NAME }}
      # AZURE_OPENAI_CHATGPT_DEPLOYMENT: ${{ vars.AZURE_OPENAI_CHATGPT_DEPLOYMENT }}
      # AZURE_OPENAI_EMB_DEPLOYMENT: ${{ vars.AZURE_OPENAI_EMB_DEPLOYMENT }}
      # AZURE_OPENAI_RESOURCE_GROUP: ${{ vars.AZURE_OPENAI_RESOURCE_GROUP }}
      # AZURE_OPENAI_SERVICE: ${{ vars.AZURE_OPENAI_SERVICE }}
      # AZURE_SEARCH_INDEX: ${{ vars.AZURE_SEARCH_INDEX }}
      # AZURE_SEARCH_QUERY_LANGUAGE: ${{ vars.AZURE_SEARCH_QUERY_LANGUAGE }}
      # AZURE_SEARCH_QUERY_SPELLER: ${{ vars.AZURE_SEARCH_QUERY_SPELLER }}
      # AZURE_SEARCH_SEMANTIC_RANKER: ${{ vars.AZURE_SEARCH_SEMANTIC_RANKER }}
      # AZURE_SEARCH_SERVICE: ${{ vars.AZURE_SEARCH_SERVICE }}
      # AZURE_SEARCH_SERVICE_LOCATION: ${{ vars.AZURE_SEARCH_SERVICE_LOCATION }}
      # AZURE_SEARCH_SERVICE_RESOURCE_GROUP: ${{ vars.AZURE_SEARCH_SERVICE_RESOURCE_GROUP }}
      # AZURE_SEARCH_SERVICE_SKU: ${{ vars.AZURE_SEARCH_SERVICE_SKU }}
      # AZURE_SERVER_APP_ID: ${{ vars.AZURE_SERVER_APP_ID }}
      # AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
      # AZURE_STORAGE_RESOURCE_GROUP: ${{ vars.AZURE_STORAGE_RESOURCE_GROUP }}
      # AZURE_STORAGE_SKU: ${{ vars.AZURE_STORAGE_SKU }}
      # AZURE_USE_APPLICATION_INSIGHTS: ${{ vars.AZURE_USE_APPLICATION_INSIGHTS }}
      # AZURE_USE_AUTHENTICATION: ${{ vars.AZURE_USE_AUTHENTICATION }}
      # AZURE_VISION_ENDPOINT: ${{ vars.AZURE_VISION_ENDPOINT }}
      # OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
      # OPENAI_HOST: ${{ vars.OPENAI_HOST }}
      # OPENAI_ORGANIZATION: ${{ vars.OPENAI_ORGANIZATION }}
      # USE_GPT4V: ${{ vars.USE_GPT4V }}
      # USE_VECTORS: ${{ vars.USE_VECTORS }}
      # VISION_SECRET_NAME: ${{ vars.VISION_SECRET_NAME }}

      AZURE_AUTH_TENANT_ID: ""
      AZURE_APP_SERVICE_SKU: "B1"
      AZURE_DOCUMENTINTELLIGENCE_LOCATION: "eastus"
      AZURE_DOCUMENTINTELLIGENCE_RESOURCE_GROUP: "rg-demo"
      AZURE_DOCUMENTINTELLIGENCE_SERVICE: "cog-di-olkqnbmrioogm"
      AZURE_ENV_NAME: "demo"
      AZURE_KEY_VAULT_NAME: ""
      AZURE_LOCATION: "canadaeast"
      AZURE_OPENAI_CHATGPT_DEPLOYMENT: "chat"
      AZURE_OPENAI_CHATGPT_MODEL: "gpt-35-turbo"
      AZURE_OPENAI_EMB_DEPLOYMENT: "embedding"
      AZURE_OPENAI_EMB_MODEL_NAME: "text-embedding-ada-002"
      AZURE_OPENAI_GPT4V_DEPLOYMENT: "gpt-4v"
      AZURE_OPENAI_GPT4V_MODEL: "gpt-4"
      AZURE_OPENAI_RESOURCE_GROUP: "rg-demo"
      AZURE_OPENAI_SERVICE: "cog-olkqnbmrioogm"
      AZURE_RESOURCE_GROUP: "rg-demo"
      AZURE_SEARCH_INDEX: "gptkbindex"
      AZURE_SEARCH_SECRET_NAME: ""
      AZURE_SEARCH_SEMANTIC_RANKER: "free"
      AZURE_SEARCH_SERVICE: "gptkb-olkqnbmrioogm"
      AZURE_SEARCH_SERVICE_ASSIGNED_USERID: "449e01fd-4926-4203-a65c-261e7542cc8a"
      AZURE_SEARCH_SERVICE_RESOURCE_GROUP: "rg-demo"
      AZURE_STORAGE_ACCOUNT: "stolkqnbmrioogm"
      AZURE_STORAGE_CONTAINER: "content"
      AZURE_STORAGE_RESOURCE_GROUP: "rg-demo"
      AZURE_SUBSCRIPTION_ID: "78505cf5-c124-41ef-8f92-79518066862a"
      AZURE_TENANT_ID: ""
      AZURE_USE_AUTHENTICATION: "false"
      AZURE_VISION_ENDPOINT: ""
      BACKEND_URI: "https://app-backend-olkqnbmrioogm.azurewebsites.net"
      OPENAI_API_KEY: ""
      OPENAI_HOST: "azure"
      OPENAI_ORGANIZATION: ""
      USE_FEATURE_INT_VECTORIZATION: "false"

    steps:
      - uses: actions/checkout@v3
        with:
          path: repo

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./repo/infra/main.bicep
          parameters: ./repo/infra/main.parameters.json
          scope: subscription
          region: ${{ env.REGION }}
          deploymentMode: Validation # Incremental